APP_NAME = "AI Codebase Intelligence Platform"
APP_VERSION = "0.1.0"

DEFAULT_ENVIRONMENT = "development"
DEFAULT_DEBUG = False

DEFAULT_OLLAMA_BASE_URL = "http://localhost:11434"
DEFAULT_OLLAMA_TIMEOUT = 120
DEFAULT_CLOUD_TIMEOUT = 120

DEFAULT_TRANSLATION_PROVIDER = "ollama"
DEFAULT_CAPTION_LANGUAGE = "en"